### ISSUE TITLE
Sécurisation smart contract Voting.sol

### ISSUE THREAD

**Issue by beubeubeubeu** [beubeubeubeu/Projet3_MEDXBEN#1]
Message de BenBK : pour rappel, pour corriger la faille vous pouvez limiter le nombre de proposals, ou mieux selon moi, déporter la logique de "trouvage du gagnant" dans la fonction setVote pour enlever la boucle dans le tallyVotes

**Comment by Mkhool** [comment]
J'ai déclaré une nouvelle variable uint256 private maxVoteCount; Puis déporté la logique de tallyVotes a setVote. C'est un peu plus cher en gas mais ça permet d'éviter l'attaque Dos.

**Comment by beubeubeubeu** [comment]
Yes j'ai vu ça, je pense que c'est la bonne logique. 

En micro optimisation on peut ne pas déclarer maxVoteCount et lire directement le voteCount de la winning proposal en cours au moment d'un nouveau vote mais bon.
