### ISSUE TITLE
Editer le README (cf.description)

### ISSUE THREAD

**Issue by beubeubeubeu** [beubeubeubeu/Projet3_MEDXBEN#25]
Template de Cyril:

# Dapp Voting

## Pour correction :

Lien vidéo: LINK  
Lien Déploiement: LINK   
Déployé sur sépolia

Groupe constitué de :  
Jean Martin et  
Alice Dupont

### Contract
La faille a été corrigé comme suit:  

Niveaux bonnes pratiques nous avons fait ceci:  

### Testing
Rien a faire ici

### Front
Voici la liste de la stack utilisée pour la réalisation du projet
- truc
- truc

**Comment by Mkhool** [comment]
A compléter quand on aura les derniers liens
